### ISSUE TITLE
Map AS link "kind" based on known URL patterns

### ISSUE THREAD

**Issue by hakbailey** [MITLibraries/mario#100]
The link "kind" field can be determined for some known URL patterns. Currently known patterns include links starting with:

- `https://wayback.archive-it.org/7963/`: links to institute web pages archived in the Wayback Machine.
- `http://hdl.handle.net/1721.3/`: links to digital objects in Dome.
- `https://dspace.mit.edu/handle/1721.1/`: links to digital objects in DSpace@MIT.
- `https://libraries.mit.edu/app/dissemination/DIPonline/`: links to digital objects stored in the DIPonline file store.
- `http://library.mit.edu/item/`: link to item record in Barton (library catalog).

Http/https seem to be used arbitrarily on all of the above link types, so don't count on either for pattern matching.

We should confirm with DDC folks what the value of the "kind" field should be for each link type above.

**Comment by hmsmithmit** [comment]
moved to Jira to track in DISCO project https://mitlibraries.atlassian.net/browse/DISCO-103
