### ISSUE TITLE
Upgrade to v7

### ISSUE THREAD

**Issue by gravesm** [MITLibraries/mario#181]
We need to start working on upgrading our ES index to v7. We'll use this issue to coordinate the process across mario, timdex and aws.

- [ ] Fix #85 
- [ ] Upgrade ES instance to 6.8
- [ ] Test mario data load
- [ ] Test timdex
- [ ] Disable mario data load in airflow
- [ ] Change mapping in mario to typeless
- [ ] Manually reindex aleph and aspace indices
  - [ ] Create a new index for each with the new mapping
  - [ ] Use the [reindex api](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-reindex.html#docs-reindex) to reindex both indices
  - [ ] Update the alias to point to the new indices
- [ ] Delete any old indices without a v7 friendly name
- [ ] Re-enable the mario data load in airflow
- [ ] Upgrade ES instance to 7
- [ ] :beers:

**Comment by gravesm** [comment]
It's possible the manual reindex can just be done by manually triggering a mario run in airflow. I'm not sure whether that will force a new index or not.

**Comment by hmsmithmit** [comment]
moved this to Jira to track in the DISCO project: https://mitlibraries.atlassian.net/browse/DISCO-89
note: added checklist items as subtasks, added linked/referenced items in descriptions where appropriate.
