### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by hakbailey** [MITLibraries/mario#190]
Doesn't look like they've been updated since we added the archives parser. Maybe also link to TIMDEX docs since the full pipeline > es > timdex local testing process is documented there.

**Comment by JPrevost** [comment]
Please update the code to reflect the current state of the documentation. Thanks.

**Comment by JPrevost** [comment]
(also, your plan is better let's do that instead)

**Comment by hmsmithmit** [comment]
Moved to Jira to track in DISCO project https://mitlibraries.atlassian.net/browse/DISCO-106
