### ISSUE TITLE
Switch to partitioned S3 bucket

### ISSUE THREAD

**Issue by gravesm** [MITLibraries/mario#252]
See: https://github.com/MITLibraries/mario/blob/master/docs/architecture-decisions/0015-use-a-single-bucket.md

The source name (#251) should be used consistently throughout as both the S3 prefix and the ES index prefix. This work will need to be coordinated with the external scripts dumping data into the bucket.

**Comment by hmsmithmit** [comment]
Moved to Jira to track in DISCO project https://mitlibraries.atlassian.net/browse/DISCO-111
