### ISSUE TITLE
Don't promote index before sanity check

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/mario#275]
Develop simple sanity check before promoting index

Possibly something like "the total number of records dropped by less than 1% compared to the current production aleph index".

If our check fails, don't promote but do somehow trigger an alert for a human to manual look at the new and old indexes and promote manually if it was fine or fix it if it wasn't.

**Comment by hmsmithmit** [comment]
Moved to Jira to track in DISCO project https://mitlibraries.atlassian.net/browse/DISCO-115
