### ISSUE TITLE
no active connection found: no Elasticsearch node available

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/mario#40]
If you run into that when using docker, you probably need to add some additional parameters to your docker command.

This seems to work:

```
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "xpack.security.enabled=false" -e network.host=_local_,_site_ -e network.publish_host=_local_ docker.elastic.co/elasticsearch/elasticsearch:6.4.2
```

More info:
https://github.com/olivere/elastic/wiki/Sniffing
https://github.com/olivere/elastic/wiki/Docker

**Comment by JPrevost** [comment]
The solution is to probably just add this to README but putting it here for deciding later what to do.

**Comment by hmsmithmit** [comment]
Moved to Jira to track in DISCO project https://mitlibraries.atlassian.net/browse/DISCO-101
