### ISSUE TITLE
Rewrite Makefile promote command for new AWS accounts

### ISSUE THREAD

**Issue by hakbailey** [MITLibraries/mario#581]
The `promote` command in the [Makefile](https://github.com/MITLibraries/mario/blob/22421d71d5b83e552d6c8afd983c549e63596eef/Makefile#L31) currently uses our single account infrastructure to promote the container from staging to production. This needs to be rewritten to work in our new infrastructure where we have different accounts for stage and prod.

**Comment by cabutlermit** [comment]
@hakbailey Was this addressed by PR#587?

**Comment by hakbailey** [comment]
It has definitely been addressed, not sure by which PR but we can close it :)
