### ISSUE TITLE
Tune the indexing process

### ISSUE THREAD

**Issue by gravesm** [MITLibraries/mario#64]
Likely, a few quick changes to https://github.com/MITLibraries/mario/blob/master/main.go#L115 increasing the number of workers and size of bulk request will help.

https://github.com/olivere/elastic/wiki/BulkProcessor#list-of-options

**Comment by hmsmithmit** [comment]
Moved to Jira to track in DISCO project https://mitlibraries.atlassian.net/browse/DISCO-102
